apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: admin-web 
  namespace: nsgr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app : admin-web
    spec:
      containers:
        - name: admin-web
          image: gymrabbit/admin-web:KVERSION
          imagePullPolicy: Always
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-web
  name: admin-web
  namespace: nsgr
spec:
  type: NodePort
  ports:
  - name: admin-web
    port: 80
    protocol: TCP
  selector:
    app: admin-web
